version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  jira-server:
    build:
      context: .
    container_name: jira-server
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    depends_on:
      - jira-server
    ports:
      - "80:80"

volumes:
  db_data:
